# Generated by Django 5.0.4 on 2024-05-06 17:34

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('tank', 'Танк'), ('not a tank', 'не Танк'), ('definetely not a tank', 'вообще не Танк')], max_length=25),
        ),
        migrations.RemoveField(
            model_name='respond',
            name='ticket',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.CreateModel(
            name='Responds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Respond',
        ),
    ]
