# Generated by Django 5.0.4 on 2024-05-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responds',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
