# Generated by Django 5.0.4 on 2024-05-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_news_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('tank', 'Tank'), ('healer', 'healer'), ('dd', 'Damage dealer'), ('merchant', 'Merchant'), ('guildmaster', 'Guildmaster'), ('questgiver', 'Questgiver'), ('blacksmith', 'Blacksmith'), ('tanner', 'Tanner'), ('potionmaker', 'Potionmaker'), ('spellmaster', 'Spellmaster')], max_length=25),
        ),
    ]
