# Generated by Django 5.0.4 on 2024-05-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_responds_responder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
