# Generated by Django 5.0.4 on 2024-05-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimecode',
            name='email',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onetimecode',
            name='password',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='username',
            field=models.CharField(max_length=256),
        ),
    ]
